services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports: "3000:3000"

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db-data:/ver/lib/mysql
volumes:
  db-data:
